import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import ResponsiveAppBar from "./components/AppBar";

const projects = [
  'Templating Engine for Team Reports',
  'Executive Dashboards (Lots of DB Work, building a basic OLTP)',
  'Automated Release Notes from Youtrack and Jira',
  'Data Migration Libraries',
  'Time Tracking DB',
  'Stateless Confluence Article Templater and Updater (Connected Smartsheet, YT, Jira)',
]


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        textAlign: 'center'
      }}>
        <ResponsiveAppBar></ResponsiveAppBar>
        <p>Dev</p>
        <ul style={{textAlign: 'left', marginTop: '2rem'}}>
          {projects.map((project) => <li>{project}</li>)}
        </ul>

      </div>
    </>
  );
};

export default Home;
