import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import ResponsiveAppBar from "./components/AppBar";
import { Parallax, ParallaxLayer } from '@react-spring/parallax'

const bg_image_1 = 'https://images.unsplash.com/photo-1660840051745-2c0da0466381'
const bg_image_2 = 'https://images.pexels.com/photos/824572/pexels-photo-824572.jpeg'

const Home: NextPage = () => {
  // const { data, isLoading } = trpc.useQuery([
  //   "example.hello",
  //   { text: "from tRPC" },
  // ]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        textAlign: 'center'
      }}>
        <ResponsiveAppBar></ResponsiveAppBar>
        <Parallax pages={4}>
          <ParallaxLayer
            offset={0}
            speed={1}
            factor={2}
            style={{
              backgroundImage: `url(${bg_image_1})`,
              backgroundSize: 'cover'
            }}
          ></ParallaxLayer>
          <ParallaxLayer
            offset={1}
            speed={1}
            factor={2}
            style={{
              backgroundImage:  `url(${bg_image_2})`,
              backgroundSize: 'cover'
            }}
          ></ParallaxLayer>
          <ParallaxLayer
            offset={0.2}
            speed={0.1}
          ><h1
          style={{ fontSize: '100px'}}
          >Hello</h1></ParallaxLayer>
          <ParallaxLayer
            offset={1.3}
            speed={0.4}
          ><h1
          style={{ fontSize: '100px'}}
          >World</h1></ParallaxLayer>
        </Parallax>
        {/* <p>Home page</p> */}
      </div>
    </>
  );
};

export default Home;
