import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import ResponsiveAppBar from "./components/AppBar";

const projects = [
  'Service Request Workflow',
  'Professional Service Work Package Workflow (v1, v2, v3)',
  'Release Notes Handoffs',
  'Engineering Jira Design',
  'FHIR Implementation Design',
]

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        textAlign: 'center'
      }}>
        <ResponsiveAppBar></ResponsiveAppBar>
        <p>Projects</p>
        <ul style={{textAlign: 'left', marginTop: '2rem'}}>
          {projects.map((project) => <li>{project}</li>)}
        </ul>
      </div>
    </>
  );
};

export default Home;
